export const data = [
  {
    name: "Man Running",
    category: "people",
    price: 3.89,
    currency: "USD",
    image: {
      src: "https://images.pexels.com/photos/235922/pexels-photo-235922.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      alt: "Man Running",
    },
    bestseller: true,
    featured: false,
    details: null,
  },
  {
    name: "Girl Skating",
    category: "food",
    price: 93.89,
    currency: "USD",
    image:
      "https://images.pexels.com/photos/1250643/pexels-photo-1250643.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Camera Woman",
    category: "people",
    price: 100,
    currency: "USD",
    image: {
      src: "https://images.pexels.com/photos/610294/pexels-photo-610294.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      alt: "Camera Woman",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Running Woman",
    category: "people",
    price: 100,
    currency: "USD",
    image: {
      src: "https://images.pexels.com/photos/878151/pexels-photo-878151.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      alt: "Running Woman",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "sea Woman",
    category: "people",
    price: 100,
    currency: "USD",
    image: {
      src: "https://images.pexels.com/photos/1049628/pexels-photo-1049628.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      alt: "sea Woman",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "business people",
    category: "people",
    price: 100,
    currency: "USD",
    image: {
      src: "https://images.pexels.com/photos/2422280/pexels-photo-2422280.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      alt: "business people",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Running Woman Wall",
    category: "people",
    price: 100,
    currency: "USD",
    image: {
      src: "https://images.pexels.com/photos/1013329/pexels-photo-1013329.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      alt: "Running Woman Wall",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Happy Dad",
    category: "people",
    price: 100,
    currency: "USD",
    image: {
      src: "https://images.pexels.com/photos/853408/pexels-photo-853408.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      alt: "happy dad",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Wave Riders",
    category: "people",
    price: 100,
    currency: "USD",
    image: {
      src: "https://images.pexels.com/photos/1667018/pexels-photo-1667018.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      alt: "Wave Riders",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Cute Dog",
    category: "people",
    price: 100,
    currency: "USD",
    image: {
      src: "https://images.pexels.com/photos/981062/pexels-photo-981062.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      alt: "Cute Dog",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Startup Founders",
    category: "people",
    price: 100,
    currency: "USD",
    image: {
      src: "https://images.pexels.com/photos/2422290/pexels-photo-2422290.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      alt: "Startup Founders",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Traveller",
    category: "people",
    price: 100,
    currency: "USD",
    image: {
      src: "https://images.pexels.com/photos/845457/pexels-photo-845457.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      alt: "Traveller",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Camera Woman",
    category: "people",
    price: 100,
    currency: "USD",
    image: {
      src: "https://images.pexels.com/photos/610294/pexels-photo-610294.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      alt: "Camera Woman",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Runner",
    category: "people",
    price: 100,
    currency: "USD",
    image: {
      src: "https://images.pexels.com/photos/601177/pexels-photo-601177.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      alt: "Runner",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Reading Wild",
    category: "people",
    price: 100,
    currency: "USD",
    image: {
      src: "https://images.pexels.com/photos/267684/pexels-photo-267684.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      alt: "Reading Wild",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Basketball",
    category: "people",
    price: 100,
    currency: "USD",
    image: {
      src: "https://images.pexels.com/photos/163452/basketball-dunk-blue-game-163452.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      alt: "Basketball",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Yoga Healthy food",
    category: "people",
    price: 100,
    currency: "USD",
    image: {
      src: "https://images.pexels.com/photos/1153370/pexels-photo-1153370.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      alt: "Yoga Healthy food",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "colleagues funny",
    category: "people",
    price: 100,
    currency: "USD",
    image: {
      src: "https://images.pexels.com/photos/1206059/pexels-photo-1206059.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      alt: "colleagues funny",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Camera Woman",
    category: "people",
    price: 100,
    currency: "USD",
    image: {
      src: "https://images.pexels.com/photos/610294/pexels-photo-610294.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      alt: "Camera Woman",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Sea Man Exercise",
    category: "people",
    price: 100,
    currency: "USD",
    image: {
      src: "https://images.pexels.com/photos/414012/pexels-photo-414012.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      alt: "Sea Man Exercise",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Gentleman Travel",
    category: "people",
    price: 100,
    currency: "USD",
    image: {
      src: "https://images.pexels.com/photos/837129/pexels-photo-837129.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      alt: "gentleman travel",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Architecture",
    category: "landmarks",
    price: 101,
    currency: "USD",
    dimmentions: {
      width: 1020,
      height: 1020,
    },
    image:
      "https://images.pexels.com/photos/4049990/pexels-photo-4049990.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Samurai King Restling",
    category: "landmarks",
    price: 101,
    currency: "USD",
    image: {
      src: "https://images.pexels.com/photos/4048182/pexels-photo-4048182.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      alt: "Samurai King Restling",
    },
    bestseller: false,
    featured: true,
    details: {
      dimmentions: {
        width: 1020,
        height: 1020,
      },
      size: 15000,
      description:
        "So how did the classical Latin become so incoherent? According to McClintock, a 15th century typesetter likely",
      recommendations: [
        {
          src: "https://images.pexels.com/photos/3771836/pexels-photo-3771836.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
          alt: "woman field sun",
        },
        {
          src: "https://images.pexels.com/photos/3662910/pexels-photo-3662910.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
          alt: "happy family",
        },
        {
          src: "https://images.pexels.com/photos/2529375/pexels-photo-2529375.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
          alt: "yoga woman",
        },
      ],
    },
  },
];
